### ISSUE TITLE
Not able to load configuration from https://config.unityads.unity3d.com/webview/3.7.5/release/config.json

### ISSUE THREAD

**Issue by japsimrans13** [pavelzaichyk/flutter_unity_ads#12]
Not able to load the configuration JSON file, and hence ad doesn't show up. 
But works with VPN, so could be an ISP issue or something else.
Many other Indian developers are facing this issue. 
So anyway to fetch config file without using VPN in India.
Any help will be appreciated, Thanks in Advance.

**Comment by japsimrans13** [comment]
Updated Comment : 
I tested few more things and found that the ads were showing if I use my cellular network (Jio 4g) but the issue arises when I use my wifi broadband {"Broadband Service Provider": "Netplus"}

**Comment by pavzay** [comment]
There are several threads on Unity Ads forum about the same problem:
https://forum.unity.com/threads/unity-ads-not-getting-on-my-android-device.1022413/
https://forum.unity.com/threads/stuck-on-unity-ads-init-load-configuration.1006388/
https://forum.unity.com/threads/not-receiving-any-ads-even-in-te.442812/

It's better to report your problem here https://forum.unity.com/forums/unity-ads.67/
